# Netlify 配置文件

# 默认的构建设置
[build]
  # 将整个项目作为发布目录
  publish = "/"

# 重定向规则
[[redirects]]
  # 当用户直接访问根域名时
  from = "/"
  # 根据浏览器语言设置进行跳转
  # 将所有中文用户（zh-CN, zh-SG, zh-TW, zh-HK）导向 /zh/ 目录
  to = "/zh/"
  status = 302
  force = true
  conditions = {Language = ["zh", "zh-cn", "zh-sg", "zh-tw", "zh-hk"]}

[[redirects]]
  # 将所有其他语言的用户（包括英文）导向 /en/ 目录
  from = "/"
  to = "/en/"
  status = 302
  force = true